-- Tabela PESSOA
CREATE TABLE PESSOA (
  CODPESSOA INT PRIMARY KEY,
  NOME VARCHAR(100),
  IDADE INT,
  SEXO VARCHAR(50)
);

-- Tabela FUNCIONARIO
CREATE TABLE FUNCIONARIO (
  CODFUNCIONARIO INT PRIMARY KEY,
  CARGO VARCHAR(50),
  PONTOS INT,
  CODPESSOA INT,
  FOREIGN KEY (CODPESSOA) REFERENCES PESSOA(CODPESSOA)
);

-- Tabela CLIENTES
CREATE TABLE CLIENTES (
  CODCLIENTE INT PRIMARY KEY,
  TELEFONE INT,
  EMAIL VARCHAR(100),
  CODPESSOA INT,
  FOREIGN KEY (CODPESSOA) REFERENCES PESSOA(CODPESSOA)
);

-- Tabela PEDIDOS
CREATE TABLE PEDIDOS (
  CODPEDIDO INT PRIMARY KEY,
  QTDPEDIDO INT,
  PRECO DECIMAL(4,2)
);

-- Tabela VENDAS
CREATE TABLE VENDAS (
  CODVENDA INT PRIMARY KEY,
  SITUACAO VARCHAR(50),
  DATA DATE,
  VALORTOTAL DECIMAL(5,2)
);

-- Tabela ESTOQUE
CREATE TABLE ESTOQUE (
  CODPRODUTO INT PRIMARY KEY,
  QUANTIDADE INT,
  FORNECEDOR VARCHAR(50),
  NOMEPRODUTO VARCHAR(50)
);

-- Tabela MOTOBOY
CREATE TABLE MOTOBOY (
  CODMOTOQUEIRO INT PRIMARY KEY,
  NOME VARCHAR(50),
  PLACA VARCHAR(6),
  CODFUNCIONARIO INT,
  FOREIGN KEY (CODFUNCIONARIO) REFERENCES FUNCIONARIO(CODFUNCIONARIO)
);

-- Tabela ATENDENTE
CREATE TABLE ATENDENTE (
  CODATENDENTE INT PRIMARY KEY,
  CODFUNCIONARIO INT,
  FOREIGN KEY (CODFUNCIONARIO) REFERENCES FUNCIONARIO(CODFUNCIONARIO)
);

-- Tabela ENDERECO
CREATE TABLE ENDERECO (
  IDENDERECO INT PRIMARY KEY,
  ENDERECO VARCHAR(100),
  NUMERO INT,
  CODCLIENTE INT,
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES(CODCLIENTE)
);

-- Tabela PAGAMENTO
CREATE TABLE PAGAMENTO (
  CODPAGAMENTO INT PRIMARY KEY,
  VALOR DECIMAL(5,3),
  CODCLIENTE INT,
  FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES(CODCLIENTE)
);

-- Tabela Rota de entrega
CREATE TABLE ROTA_ENTREGA (
  CODMOTOQUEIRO INT,
  IDENDERECO INT,
  PRIMARY KEY (CODMOTOQUEIRO, IDENDERECO),
  FOREIGN KEY (CODMOTOQUEIRO) REFERENCES MOTOBOY(CODMOTOQUEIRO),
  FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO(IDENDERECO)
);

-- Tabela forma de pagamento
CREATE TABLE FORMA_PAGAMENTO (
  CODPAGAMENTO INT,
  CODPEDIDO INT,
  PRIMARY KEY (CODPAGAMENTO, CODPEDIDO),
  FOREIGN KEY (CODPAGAMENTO) REFERENCES PAGAMENTO(CODPAGAMENTO),
  FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDOS(CODPEDIDO)
);

-- Tabela alterações pedidos e estoque
CREATE TABLE ALTERACOES_PEDIDOS_ESTOQUE (
  CODPEDIDO INT,
  CODPRODUTO INT,
  PRIMARY KEY (CODPEDIDO, CODPRODUTO),
  FOREIGN KEY (CODPEDIDO) REFERENCES PEDIDOS(CODPEDIDO),
  FOREIGN KEY (CODPRODUTO) REFERENCES ESTOQUE(CODPRODUTO)
);
